accounts/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.contrib.auth import views as auth_views

from accounts import views

urlpatterns = [
    # Accounts
    url(r'^accounts/signup/$', views.signup, name='signup'),
    url(r'^accounts/account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^accounts/activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(), name='logout'),

    # Change password
    url(r'^accounts/password/change/$', views.change_password, name='password_change'),

    # Password reset
    url(r'^accounts/password/reset/$', auth_views.password_reset, {'template_name': 'accounts/registration/password_reset_form.html'}, name='password_reset'),
    url(r'^accounts/password/reset/done/$', auth_views.password_reset_done, {'template_name': 'accounts/registration/password_reset_done.html'}, name='password_reset_done'),
    url(r'^accounts/password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {'template_name': 'accounts/registration/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^accounts/password/reset/complete/$', auth_views.password_reset_complete, {'template_name': 'accounts/registration/password_reset_complete.html'}, name='password_reset_complete'),

    # Dashboard
    url(r'^settings/$', views.edit_profile, name='settings'),
    url(r'^change_status/(?P<status>[-\w]+)/$', views.change_user_status, name='change_status'),

    url(r"^lookup_users/?$", views.search_for_users, name='users-lookup')

]

cal/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from cal import views

urlpatterns = [
    # Calendar
    #url(r'^calendar/$', views.calendar, name='calendar'),
    url(r'^calendar/$', views.EventView.as_view(), name='calendar'),
    url(r'^calendar/view/(?P<pk>[0-9]+)/$', views.event_view, name='event_view'),
    url(r'^calendar/edit/(?P<pk>[0-9]+)/$', views.event_edit, name='event_edit'),
]

mywasi/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from core import views as core_views

urlpatterns = [
    # Admin & home
    url(r'^admin/', admin.site.urls),

    # Core
    url(r'', include('core.urls')),

    # Accounts
    url(r'', include('accounts.urls')),

    # Dashboard
    # Properties
    url(r'', include('properties.urls')),

    # Calendar
    url(r'', include('cal.urls')),

    # Core
    url(r'', include('core.urls')),

    # Offers
    url(r'', include('offers.urls')),

    # Blog
    url(r'', include('blog.urls')),

    #chat
    url(r'^', include('chat.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from accounts.choices import *

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/profile/{1}'.format(instance.user.id, filename)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)
    image = models.ImageField(upload_to=user_directory_path, blank=True, null=True)
    phone = models.CharField(max_length=10, blank=False, null=True)
    dni = models.CharField(max_length=9, blank=True, null=True)
    company_name = models.CharField(max_length=254, blank=True)
    nif = models.CharField(max_length=10, blank=True)
    billing_address = models.CharField(max_length=254, blank=True)
    business_email = models.EmailField(blank=True)
    status = models.CharField(max_length=10, choices=USER_STATUS, default='seller')


    def __unicode__(self):
        return self.user.email


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, created, **kwargs):
    instance.profile.save()

accounts/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from accounts.models import Profile

class SignUpForm(UserCreationForm):
    name = forms.CharField(label="Nombre y apellidos", max_length=30)
    email = forms.EmailField(max_length=256)

    class Meta:
        model = User
        fields = ('name', 'email', 'password1')
        exclude = ['username', ]

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields.pop('password2')

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise ValidationError('Email already exists', code='invalid')
        return email

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.username =  self.cleaned_data['email']
        user.first_name = self.cleaned_data['name'].split(' ')[0].capitalize()
        last_name = self.cleaned_data['name'].split(' ')
        if len(last_name) == 3:
            user.last_name = self.cleaned_data['name'].split(' ')[1].capitalize() + ' ' + self.cleaned_data['name'].split(' ')[2].capitalize()
        elif len(last_name) == 2:
            user.last_name = self.cleaned_data['name'].split(' ')[1].capitalize()
        else:
            pass

        if commit:
            user.save()
        return user


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email',)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user',]


class StatusForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('status',)

accounts/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from django.contrib.auth import login, authenticate, update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.core.mail import send_mail

from accounts.forms import SignUpForm, UserForm, ProfileForm, StatusForm
from accounts.tokens import account_activation_token
from accounts.models import Profile


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            message = render_to_string('accounts/registration/account_activation_email.html', {
                'user': user,
                'domain': 'mywasi.com',
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            send_mail('Verify your Mywasi account', message, 'hello@himynameismik.com', [user.email])

            return redirect('account_activation_sent')
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})


def account_activation_sent(request):
    return render(request, 'accounts/registration/account_activation_sent.html', {})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        return redirect('properties')
    else:
        return render(request, 'accounts/registration/account_activation_invalid.html', {})


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Tu contraseña ha sido actualizada!')
            return redirect('password_change')
        else:
            messages.error(request, 'Por favor, corrija los errores.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/registration/password_change_form.html', {'form': form})


@login_required
def edit_profile(request):
    user = get_object_or_404(User, pk=request.user.pk)
    profile = get_object_or_404(Profile, user=request.user.pk)
    if request.method == 'POST':
        uform = UserForm(request.POST, instance=user)
        pform = ProfileForm(request.POST, request.FILES, instance=profile)

        if uform.is_valid() and pform.is_valid():
            user = uform.save()
            profile = pform.save(commit=False)
            profile.user = user
            profile.save()
    else:
        uform = UserForm(instance=user)
        pform = ProfileForm(instance=profile)
    return render(request, 'dashboard/settings.html', {'uform': uform, 'pform': pform})


def change_user_status(request, status):
    user = get_object_or_404(User, pk=request.user.pk)
    user.profile.status = status
    user.save()
    return redirect('properties')


@login_required
def search_for_users(request):

    query = request.GET.get('term')
    if query and request.is_ajax():
        suggestions = Profile.objects.filter(Q(user__first_name__icontains=query) | Q(user__last_name__icontains=query) | Q(user__email__icontains=query) | Q(phone__icontains=query), user__is_superuser=False).exclude(user_id=request.user.id)
        if suggestions.exists():
            context = {
                'profiles': suggestions,
                'term': query,
            }
            return render_to_response('chat/partials/suggestions.html', context)

    return HttpResponse('')

templates/accounts/accounts_base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="keywords" content="">

    {% block title %}
    {% endblock %}

    <!-- Styles -->
    <link href="{% static 'css/core.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/thesaas.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="{% static 'img/apple-touch-icon.png' %}">
    <link rel="icon" href="{% static 'img/favicon.png' %}">
  </head>

  <body>
    {% block content %}
    {% endblock %}

    <!-- Scripts -->
    <script src="{% static 'js/core.min.js' %}"></script>
    <script src="{% static 'js/thesaas.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

templates/accounts/login.html
{% extends 'accounts/accounts_base.html' %}
{% load staticfiles %}

{% block title %}
<title>Mywasi - Login</title>
{% endblock %}

{% block content %}
<dir class="row no-gap">
  <div class="col-12 col-md-6 mh-fullscreen bg-img center-vh" align="center" style="background-color: #fafbfc;" >
    <br>
    <div class="card card-shadowed p-50 w-400" style="max-width: 100%">
      <h4 class="text-uppercase text-left">Bienvenido a MyWasi!</h4>
      <br>
      <form class="form-type-material" method="POST">{% csrf_token %}
        {% include 'includes/form.html' %}
        <button class="btn btn-bold btn-primary" style="float: right" type="submit">Entrar</button>
      </form>

      <p class="text-center text-muted fs-13 mt-20">Aun no tienes una cuenta? <a href="{% url 'valuation' %}">Valora tu casa</a></p>
        <span class="custom-control-description"><a class="text-primary fs-10" href="{% url 'password_reset' %}">¿Olvidaste tu contraseña?</a></span>
    </div>
  </div>
  <div class="col-12 col-md-6 mh-fullscreen bg-img center-vh" align="center" style="background: url({% static 'img/form_bg.png' %}); background-size:cover;">
    <div class="card-outline-primary ml-50 mr-50 w-500">
      <h4 class="text-white text-left">Ahorrate hasta 15.000€ con la venta de tu casa.</h4>
      <h6 class="text-white text-left">Nuestra plataforma te permitirá ahorrarte ese dinero
          para que puedas invertirlo en una cocina, una piscina o unas vacaciones maravillosas
          para celebrarlo! Y todo esos...en menos de 2 meses!</h6>
      <h6 class="text-white text-left"> A que esperas para cambiar tu vida?</h6>
    </div>
  </div>
</dir>
{% endblock %}

templates/accounts/signup.html
{% extends 'accounts/accounts_base.html' %}
{% load staticfiles %}

{% block title %}
<title>Mywasi - Register</title>
{% endblock %}

{% block content %}
<dir class="row no-gap" style="background-color: #fff;">
  <div class="col-12 col-md-12 mh-fullscreen bg-img center-vh" align="center"  >
    <div class="card card-shadowed" style="width: 80%">
      <dir class="row no-gap m-0">
        <div class="col-12 col-md-5 p-50" align="center" style="background-color: #fafbfc;" >
          <h4 class="text-uppercase text-left">Bienvenido a MyWasify!</h4>
          <h6 class="text-left">Resumen de los servicios contratados:</h6>
          <br>
          <div class="row card card-shadowed" style="background-color: #fff, width: 100%;">
            <div class="col-4">
              <h6 class="fs-50 mt-10"><i class="fa fa-diamond" aria-hidden="true"></i></h6>
            </div>
            <div class="col-8">
                <h6>Paquete unico</h6>
                <p>Blabalabala</p>
                <p>Blabalabala</p>
                <p>Blabalabala</p>
                <p>...</p>
                <p>€499</p>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-6 text-left">
              <b>Total:</b>
            </div>
            <div class="col-6 text-rigth">
              <b>€499</b>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-7 p-60">
          <form class="form-type-material" method="POST">{% csrf_token %}
            <h5 class="text-uppercase text-left uppercase">Proceso de pago</h5>
            <h6 class="text-left">1. Datos Personales</h6>
              {% if user.is_authenticated %}
              <br>
              <div class="row">
                <div class="col-6 text-left">
                  <b>Registrado como: </b>{{ user.first_name }} {{ user.last_name }}
                </div>
                <div class="col-6 text-rigth">
                  <button type="button" class="btn btn-inline btn-primary-outline"><a href="{% url 'logout' %}">Cambiar de usuario</a></button>
                </div>
              </div>
              <br>
              {% else %}
              <div class="row">
              {% include 'includes/form_payment.html' %}
              </div>
              {% endif %}
            <h6 class="text-left">2. Datos del pago  <i class="fa fa-lock" aria-hidden="true" style="color: black"></i></h6>
            <div class="row">
              <div class="col-12 form-group">
                <p class="text-left m-0 fs-13"><label for="id_name">Nombre en la tarjeta:</label></p>
                <input type="text" name="name" id="id_name" required="" class="form-control" maxlength="30">
              </div>
              <div class="col-8 form-group">
                <p class="text-left m-0 fs-13"><label for="id_name">Numero de la tarjeta:</label></p>
                <input type="text" name="name" id="id_name" required="" class="form-control" maxlength="30">
              </div>
              <div class="col-4 text-left fs-25">
                <p class="text-left m-0 fs-16"><label for="id_name"></label></p>
                  <i class="fa fa-cc-visa" aria-hidden="true" style="color: black"></i>
                  <i class="fa fa-cc-mastercard" aria-hidden="true" style="color: black"></i>
                  <i class="fa fa-cc-amex" aria-hidden="true" style="color: black"></i>
                  <i class="fa fa-cc-stripe" aria-hidden="true" style="color: black"></i>
              </div>
              <div class="col-6 form-group">
                <p class="text-left m-0 fs-13"><label for="id_name">Caducidad:</label></p>
                <input type="text" name="name" id="id_name" required="" class="form-control" maxlength="30">
              </div>
              <div class="col-6 form-group">
                <p class="text-left m-0 fs-13"><label for="id_name">CVV:</label></p>
                <input type="text" name="name" id="id_name" required="" class="form-control" maxlength="30">
              </div>
            </div>

            <button class="btn btn-bold btn-primary text-uppercase" style="float: center" type="submit">Contratar Servicios</button>
          </form>

          <p class="custom-control-description text-center mt-10 fs-8">Haciendo click en el botón acepta nuestros <a class="text-primary" href="#">Terminos y Política de privacidad</a></p>
        </div>
      </div>
    </div>
  </div>
</dir>
{% endblock %}

templates/accounts/signup_original.html
{% extends 'accounts/accounts_base.html' %}
{% load staticfiles %}

{% block title %}
<title>Mywasi - Register</title>
{% endblock %}

{% block content %}
<dir class="row no-gap">
  <div class="col-12 col-md-6 mh-fullscreen bg-img center-vh" align="center" style="background-color: #fafbfc;" >
    <br>
    <div class="card card-shadowed p-50 w-400" style="max-width: 100%">
      <h4 class="text-uppercase text-left">Bienvenido a MyWasify!</h4>
      <h6 class="text-left">Crea una cuenta nueva:</h6>
      <br>
      <form class="form-type-material" method="POST">{% csrf_token %}
        {% include 'includes/form.html' %}
        <br>
        <button class="btn btn-bold btn-primary" style="float: right" type="submit">Crear Cuenta</button>
      </form>

      <br>
      <p class="custom-control-description text-center m-0 fs-8">Haciendo click en el botón acepta nuestros <a class="text-primary" href="#">Terminos y Política de privacidad</a></p>
      <hr class="w-100">
      <p class="text-center text-muted fs-13 mt-20">Ya tienes una cuenta? <a href="{% url 'login' %}">Acceder</a></p>
    </div>
  </div>
  <div class="col-12 col-md-6 mh-fullscreen bg-img center-vh" align="center" style="background: url({% static 'img/form_bg.png' %}); background-size:cover;">
    <div class="card-outline-primary ml-50 mr-50 w-500">
      <h4 class="text-white text-left">Ahorrate hasta 15.000€ con la venta de tu casa.</h4>
      <h6 class="text-white text-left">Nuestra plataforma te permitirá ahorrarte ese dinero
        para que puedas invertirlo en una cocina, una piscina o unas vacaciones maravillosas
        para celebrarlo! Y todo esos...en menos de 2 meses!</h6>
      <h6 class="text-white text-left"> A que esperas para cambiar tu vida?</h6>
    </div>
  </div>
</dir>
{% endblock %}