cal/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from cal import views

urlpatterns = [
    # Calendar
    #url(r'^calendar/$', views.calendar, name='calendar'),
    url(r'^calendar/$', views.EventView.as_view(), name='calendar'),
    url(r'^calendar/view/(?P<pk>[0-9]+)/$', views.event_view, name='event_view'),
    url(r'^calendar/edit/(?P<pk>[0-9]+)/$', views.event_edit, name='event_edit'),
]

chat/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^chat/(?P<id>[0-9]+)$',
        view=views.DialogListView.as_view(),
        name='dialogs_detail'
    ),
    url(
        regex=r'^chat/$',
        view=views.DialogListView.as_view(),
        name='dialogs'
    )
]

mywasi/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from core import views as core_views

urlpatterns = [
    # Admin & home
    url(r'^admin/', admin.site.urls),

    # Core
    url(r'', include('core.urls')),

    # Accounts
    url(r'', include('accounts.urls')),

    # Dashboard
    # Properties
    url(r'', include('properties.urls')),

    # Calendar
    url(r'', include('cal.urls')),

    # Core
    url(r'', include('core.urls')),

    # Offers
    url(r'', include('offers.urls')),

    # Blog
    url(r'', include('blog.urls')),

    #chat
    url(r'^', include('chat.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

properties/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from properties import views

urlpatterns = [
    # Properties
    url(r'^properties/$', views.properties, name='properties'),
    url(r'^properties/detail/(?P<pk>[0-9]+)/$', views.property_detail, name='property_detail'),
    url(r'^properties/add/location/$', views.add_property_location, name='add_property_location'),
    url(r'^properties/add/description/$', views.add_property_description, name='add_property_description'),
    url(r'^properties/add/price/$', views.add_property_price, name='add_property_price'),
    url(r'^properties/edit/location/(?P<pk>[0-9]+)/$', views.edit_property_location, name='edit_property_location'),
    url(r'^properties/edit/description/(?P<pk>[0-9]+)/$', views.edit_property_description, name='edit_property_description'),
    url(r'^properties/edit/price/(?P<pk>[0-9]+)/$', views.edit_property_price, name='edit_property_price'),
    url(r'^properties/edit/images/(?P<pk>[0-9]+)/$', views.ImageUploadView.as_view(), name='edit_property_images'),
    url(r'^properties/edit/documents/(?P<pk>[0-9]+)/$', views.DocumentUploadView.as_view(), name='edit_property_documents'),
]

properties/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from django.core.validators import FileExtensionValidator

from properties.choices import *

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class Property(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    location = models.CharField(max_length=254, blank=False, null=True)
    number = models.IntegerField(blank=False)
    prop_type = models.CharField(max_length=10, choices=PROP_TYPE, default='flat')
    prop = models.CharField(max_length=10, choices=PROP_TYPE, default='flat')
    price = models.FloatField()
    sqm = models.IntegerField()
    util_sqm = models.IntegerField()
    prop_status = models.CharField(max_length=10, choices=PROP_STATUS, default='good')
    num_bedrooms = models.CharField(max_length=2, choices=NUMBERS, default='1')
    num_bathrooms = models.CharField(max_length=2, choices=NUMBERS, default='1')
    num_rooms = models.CharField(max_length=2, choices=NUMBERS, default='1')
    swimmingpool = models.BooleanField(default=False)
    storageroom = models.BooleanField(default=False)
    garden = models.BooleanField(default=False)
    balcony = models.BooleanField(default=False)
    wardrobe = models.BooleanField(default=False)
    hydromassage = models.BooleanField(default=False)
    lift = models.BooleanField(default=False)
    penthouse = models.BooleanField(default=False)
    garage = models.BooleanField(default=False)
    ac = models.BooleanField(default=False)
    concierge = models.BooleanField(default=False)
    cleaner = models.BooleanField(default=False)
    energetic_certificate = models.CharField(max_length=1, choices=ENERGETIC_CERTIFICATE, default='d')
    orientation = models.CharField(max_length=5, choices=ORIENTATION, default='north')
    description = models.TextField()
    #image = models.ImageField(upload_to=user_directory_path, blank=True, null=True, validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])])
    #plane = models.FileField(upload_to=user_directory_path, blank=True, null=True)
    #energetic_certificate_file = models.FileField(upload_to=user_directory_path, blank=True, null=True)
    #certificate_of_occupancy = models.FileField(upload_to=user_directory_path, blank=True, null=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return '{}, {}'.format(self.location, self.number)

    class Meta:
        verbose_name_plural = 'Properties'


def user_image_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/images/<filename>
    return 'user_{0}/images/{1}'.format(instance.prop.user.id, filename)


class Image(models.Model):
   prop = models.ForeignKey(Property)
   image = models.ImageField(upload_to=user_image_directory_path, blank=True, null=True)
   uploaded_at = models.DateTimeField(auto_now_add=True)

   def __unicode__(self):
       return '{}, {}'.format(str(self.prop.location), self.image.name)


def user_document_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/images/<filename>
    return 'user_{0}/docs/{1}'.format(instance.prop.user.id, filename)


class Document(models.Model):
   prop = models.ForeignKey(Property)
   name = models.CharField(max_length=256)
   document = models.FileField(upload_to=user_document_directory_path, blank=True, null=True)
   uploaded_at = models.DateTimeField(auto_now_add=True)

   def __unicode__(self):
       return '{}, {}'.format(str(self.prop.location), self.document.name)

properties/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth.models import User

from properties.models import Property, Image, Document

class PropertyLocationForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = ('location', 'number', 'prop_type', 'prop',)


class PropertyDescriptionForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = ('sqm', 'util_sqm', 'prop_status', 'num_bedrooms', 'num_bathrooms',
            'num_rooms', 'swimmingpool', 'storageroom', 'garden', 'balcony', 'wardrobe',
            'hydromassage', 'lift', 'penthouse', 'garage', 'ac', 'concierge', 'cleaner',
            'energetic_certificate', 'orientation', 'description',)


class PropertyPriceForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = ('price',)


class PropertyImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('image',)


class PropertyDocumentForm(forms.ModelForm):
    class Meta:
       model = Document
       fields = ('document',)

properties/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.views import View
from django.utils import timezone

from core.models import Valuation
from properties.models import Property, Image, Document
from properties.forms import PropertyLocationForm, PropertyDescriptionForm, PropertyPriceForm, PropertyImageForm, PropertyDocumentForm

def properties(request):
    properties = Property.objects.filter(user=request.user.id).order_by('updated')
    if len(properties) < 3:
        no_properties = range(3-len(properties))
    else:
        no_properties = {}
    return render(request, 'properties/properties.html', {'properties': properties, 'no_properties': no_properties})


def property_detail(request, pk):
    property = Property.objects.get(pk=pk)
    return render(request, 'properties/property_detail.html', {'property': property})

# ADD PROPERTY

def add_property_location(request):
    user = get_object_or_404(User, pk=request.user.id)
    if request.method == 'POST':
        form = PropertyLocationForm(request.POST)
        if form.is_valid():
            property = form.save(commit=False)
            property.user = user
            property.price = 0
            property.sqm = 0
            property.util_sqm = 0
            property.save()
        return redirect('add_property_description')

    else:
        form = PropertyLocationForm()
    return render(request, 'properties/add_edit_location.html', {'form': form})


def add_property_description(request):
    property = Property.objects.filter(user=request.user).latest('updated')
    if request.method == 'POST':
        form = PropertyDescriptionForm(request.POST, instance=property)
        if form.is_valid():
            form.save()
        return redirect('add_property_price')

    else:
        form = PropertyDescriptionForm(instance=property)
    return render(request, 'properties/add_edit_description.html', {'form': form})


def add_property_price(request):
    property = Property.objects.filter(user=request.user).latest('updated')
    if request.method == 'POST':
        form = PropertyPriceForm(request.POST, instance=property)
        if form.is_valid():
            form.save()
        return redirect('properties')

    else:
        form = PropertyPriceForm(instance=property)
    return render(request, 'properties/add_edit_price.html', {'form': form})

# EDIT PROPERTY

def edit_property_location(request, pk):
    property = get_object_or_404(Property, pk=pk)
    if request.method == 'POST':
        form = PropertyLocationForm(request.POST, instance=property)
        if form.is_valid():
            form.save()
        return redirect('edit_property_description', pk)

    else:
        form = PropertyLocationForm(instance=property)
    return render(request, 'properties/add_edit_location.html', {'form': form})


def edit_property_description(request, pk):
    property = get_object_or_404(Property, pk=pk)
    if request.method == 'POST':
        form = PropertyDescriptionForm(request.POST, instance=property)
        if form.is_valid():
            form.save()
        return redirect('edit_property_price', pk)

    else:
        form = PropertyDescriptionForm(instance=property)
    return render(request, 'properties/add_edit_description.html', {'form': form})


def edit_property_price(request, pk):
    property = get_object_or_404(Property, pk=pk)
    if request.method == 'POST':
        form = PropertyPriceForm(request.POST, instance=property)
        if form.is_valid():
            form.save()
        return redirect('edit_property_images', pk)

    else:
        form = PropertyPriceForm(instance=property)
    return render(request, 'properties/add_edit_price.html', {'form': form})


class ImageUploadView(View):
    def get(self, request, pk):
        photo_list = Image.objects.all().filter(prop=pk)
        return render(self.request, 'properties/add_edit_images.html', {'photo_list': photo_list})

    def post(self, request, pk):
        property = get_object_or_404(Property, pk=pk)
        form = PropertyImageForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            for f in self.request.FILES.getlist('image'):
                i = Image(prop=property, image=f)
                i.save()

        return redirect('edit_property_documents', pk=pk)


class DocumentUploadView(View):
    def get(self, request, pk):
        document_list = Document.objects.all().filter(prop=pk)
        return render(self.request, 'properties/add_edit_documents.html', {'document_list': document_list})

    def post(self, request, pk):
        property = get_object_or_404(Property, pk=pk)
        form = PropertyDocumentForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            for f in self.request.FILES.keys():
                for d in self.request.FILES.getlist(f):
                    doc = Document(prop=property, name=f, document=d)
                    doc.save()

        return redirect('properties')

templates/properties/add_edit_description.html
{% extends 'properties/property_form_base.html' %}
{% load widget_tweaks %}

{% block path %}
  Mis Propiedades > Editar Anuncio > Descripción
{% endblock %}

{% block form %}
  <div class="col-9">
    <br>
    <h7 class="text-uppercase">DESCRIPCIÓN DE LA PROPIEDAD</h7>
    <br><br>
    <form class="row gap-y" method="POST" enctype="multipart/form-data">{% csrf_token %}
      <div class="col-4">
        <div class="form-group">
          <p class="form-label text-left">Metros quadrados</p>
          {% render_field form.sqm class="form-control" %}
        </div>
      </div>
      <div class="col-4">
        <div class="form-group">
          <p class="form-label text-left">Metros quadrados útiles</p>
          {% render_field form.util_sqm class="form-control" %}
        </div>
      </div>
      <div class="col-4">
        <div class="form-group">
          <p class="form-label text-left">Estado del Inmueble</p>
          {% render_field form.prop_status class="form-control" %}
        </div>
      </div>
      <div class="col-4">
        <div class="form-group">
          <p class="form-label text-left">Habitaciones</p>
          {% render_field form.num_bedrooms class="form-control" %}
        </div>
      </div>
      <div class="col-4">
        <div class="form-group">
          <p class="form-label text-left">Baños</p>
          {% render_field form.num_bathrooms class="form-control" %}
        </div>
      </div>
      <div class="col-4">
        <div class="form-group">
          <p class="form-label text-left">Salones</p>
          {% render_field form.num_rooms class="form-control" %}
        </div>
      </div>

      <div class="col-2">
        <div class="checkbox">
						{{ form.swimmingpool }}
						<label for="id_swimmingpool">Piscina</label>
			  </div>
      </div>
      <div class="col-2">
        <div class="checkbox">
            {{ form.storageroom }}
            <label for="id_storageroom">Trastero</label>
        </div>
      </div>
      <div class="col-2">
        <div class="checkbox">
            {{ form.garden }}
            <label for="id_garden">Jardin</label>
        </div>
      </div>
      <div class="col-2">
        <div class="checkbox">
            {{ form.balcony }}
            <label for="id_balcony">Terraza</label>
        </div>
      </div>
      <div class="col-2">
        <div class="checkbox">
            {{ form.wardrobe }}
            <label for="id_wardrobe">Armarios Empotrados</label>
        </div>
      </div>
      <div class="col-2">
        <div class="checkbox">
            {{ form.hydromassage }}
            <label for="id_hydromassage">Hidromasaje</label>
        </div>
      </div>
      <div class="col-2">
        <div class="checkbox">
            {{ form.lift }}
            <label for="id_lift">Ascensor</label>
        </div>
      </div>
      <div class="col-2">
        <div class="checkbox">
            {{ form.penthouse }}
            <label for="id_penthouse">Atico</label>
        </div>
      </div>
      <div class="col-2">
        <div class="checkbox">
            {{ form.garage }}
            <label for="id_garage">Garaje</label>
        </div>
      </div>
      <div class="col-2">
        <div class="checkbox">
            {{ form.ac }}
            <label for="id_ac">Aire Acondicionado</label>
        </div>
      </div>
      <div class="col-2">
        <div class="checkbox">
          {{ form.concierge }}
          <label for="id_concierge">Conserge</label>
        </div>
      </div>
      <div class="col-2">
        <div class="checkbox">
          {{ form.cleaner }}
          <label for="id_cleaner">Limpieza</label>
        </div>
      </div>
      <div class="col-4">
        <div class="form-group">
          <p class="form-label text-left">Certificado Energetico</p>
          {% render_field form.energetic_certificate class="form-control" %}
        </div>
      </div>
      <div class="col-4">
        <div class="form-group">
          <p class="form-label text-left">Orientacion</p>
          {% render_field form.orientation class="form-control" %}
        </div>
      </div>
      <div class="col-12">
        <div class="form-group">
          <p class="form-label text-left">Descripción</p>
          {% render_field form.description class="form-control" rows="4" placeholder="Escribe aqui la descripción de la propiedad..." %}
        </div>
      </div>

      <div class="col-9"></div>
      <div class="col-2">
        <button class="btn btn-bold btn-primary" type="submit">Siguiente</button>
      </div>
    </form>
  </div>
{% endblock %}

templates/properties/add_edit_documents.html
{% extends 'properties/property_form_base.html' %}
{% load widget_tweaks %}

{% block path %}
  Mis Propiedades > Editar Anuncio > Documentos
{% endblock %}

{% block form %}
  <div class="col-9">
    <br>
    <h7 class="text-uppercase">DOCUMENTOS DE LA PROPIEDAD</h7>
    <br><br>
    <form class="row gap-y" method="POST" enctype="multipart/form-data">{% csrf_token %}
      <div class="col-12">
        <div class="form-group">
          <p class="form-label text-left">Plano de la Propiedad</p>
          <p class="form-label text-left fs-10">Añade el plano de tu propiedad. Si no tienes, puedes obtenerlo a un precio especial aquí.</p>
        </div>
        <div class="col-12 drop-zone dragover">
            <i class="font-icon font-icon-cloud-upload-2"></i>
            <div class="drop-zone-caption">Drag file to upload</div>
            <span class="btn btn-rounded btn-file">
                <span>Choose file</span>
                <input type="file" name="plane" onchange="showfilename(this.files)" multiple>
            </span>
        </div>
      </div>
      <br />
      <div id="planeNameList"></div>
      <div>
        {% for doc in document_list %}
          {% if doc.name == 'plane' %}
            <p>Archivo actual: {{ doc.document.name }}</p>
          {% endif %}
        {% endfor %}
      </div>

      <div class="col-12">
        <div class="form-group">
          <p class="form-label text-left">Certificado Energético</p>
          <p class="form-label text-left fs-10">Edita o incluye mas fotos a tu antojo. Es muy simple!</p>
        </div>
        <div class="col-12 drop-zone dragover">
            <i class="font-icon font-icon-cloud-upload-2"></i>
            <div class="drop-zone-caption">Drag file to upload</div>
            <span class="btn btn-rounded btn-file">
                <span>Choose file</span>
                <input type="file" name="energetic_certificate" onchange="showecname(this.files)">
            </span>
        </div>
      </div>
      <br />
      <div id="ecNameList"></div>
      <div>
        {% for doc in document_list %}
          {% if doc.name == 'energetic_certificate' %}
            <p>Archivo actual: {{ doc.document.name }}</p>
          {% endif %}
        {% endfor %}
      </div>

      <div class="col-12">
        <div class="form-group">
          <p class="form-label text-left">Cédula de habitabilidad</p>
          <p class="form-label text-left fs-10">Edita o incluye mas fotos a tu antojo. Es muy simple!</p>
        </div>
        <div class="col-12 drop-zone dragover">
            <i class="font-icon font-icon-cloud-upload-2"></i>
            <div class="drop-zone-caption">Drag file to upload</div>
            <span class="btn btn-rounded btn-file">
                <span>Choose file</span>
                <input type="file" name="certificate_of_occupancy" onchange="showcooname(this.files)">
            </span>
        </div>
      </div>
      <br />
      <div id="cooNameList"></div>
      <div>
        {% for doc in document_list %}
          {% if doc.name == 'certificate_of_occupancy' %}
            <p>Archivo actual: {{ doc.document.name }}</p>
          {% endif %}
        {% endfor %}
      </div>

      <div class="col-9"></div>
      <div class="col-2">
        <button class="btn btn-bold btn-primary" type="submit">Siguiente</button>
      </div>
    </form>
  </div>
{% endblock %}

{% block scripts %}
  <script>
    function showfilename(files) {
      for (var i = 0; i < files.length; i++) {
        $("#planeNameList").append("Nuevo archivo: " + files[i].name + "<br />");
      }
    }
  </script>

  <script>
    function showecname(files) {
      for (var i = 0; i < files.length; i++) {
        $("#ecNameList").append("Nuevo archivo: " + files[i].name + "<br />");
      }
    }
  </script>

  <script>
    function showcooname(files) {
      for (var i = 0; i < files.length; i++) {
        $("#cooNameList").append("Nuevo archivo: " + files[i].name + "<br />");
      }
    }
  </script>
{% endblock %}

templates/properties/add_edit_images.html
{% extends 'properties/property_form_base.html' %}
{% load widget_tweaks %}

{% block path %}
  Mis Propiedades > Editar Anuncio > Fotografías y planos
{% endblock %}

{% block form %}
  <div class="col-9">
    <br>
    <h7 class="text-uppercase">Fotografias y Planos</h7>
    <br><br>
    <form class="row gap-y" method="POST" enctype="multipart/form-data">{% csrf_token %}
      <div class="col-12">
        <div class="form-group">
          <p class="form-label text-left">Fotografias de tu Propiedad</p>
          <p class="form-label text-left fs-10">Edita o incluye mas fotos a tu antojo. Es muy simple!</p>
        </div>
        {% for photo in photo_list %}
          <img src="{{ photo.image.url }}" alt="image" width="128px" height="auto">
        {% endfor %}
        <div class="col-12 drop-zone dragover">
            <i class="font-icon font-icon-cloud-upload-2"></i>
            <div class="drop-zone-caption">Drag file to upload</div>
            <span class="btn btn-rounded btn-file">
                <span>Choose file</span>
                <input type="file" name="image" onchange="showimagename(this.files)" multiple>
            </span>
        </div>
        <br />
        <div id="imageNameList"></div>
      </div>
      <!-- <div class="col-9"></div> -->
      <div class="col-12">
        <button class="btn btn-bold btn-primary pull-right" type="submit">Siguiente</button>
      </div>
    </form>
  </div>
{% endblock %}

{% block scripts %}
  <script>
    function showimagename(files) {
      for (var i = 0; i < files.length; i++) {
        $("#imageNameList").append("Nuevo archivo: " + files[i].name + "<br />");
      }
    }
  </script>
{% endblock %}

templates/properties/add_edit_location.html
{% extends 'properties/property_form_base.html' %}
{% load widget_tweaks %}

{% block path %}
  Mis Propiedades > Editar Anuncio > Ubicación
{% endblock %}

{% block form %}
  <div class="col-9 pr-0">
    <br>
    <h7 class="text-uppercase">UBICACIÓN DE LA PROPIEDAD</h7>
    <br><br>
    <form class="row gap-y" method="POST" enctype="multipart/form-data">{% csrf_token %}
      <div class="col-8">
        <div class="form-group">
          <p class="form-label text-left">Calle y Poblacion (Sin Numero)</p>
          {% render_field form.location class="form-control" %}
        </div>
      </div>
      <div class="col-8">
        <div class="form-group">
          <p class="form-label text-left">Numero</p>
          {% render_field form.number class="form-control" %}
        </div>
      </div>
      <div class="col-8">
        <div class="form-group">
          <p class="form-label text-left">Tipo de Inmueble</p>
          {% render_field form.prop_type class="form-control" %}
        </div>
      </div>
      <div class="col-8">
        <div class="form-group">
          <p class="form-label text-left">Inmueble</p>
          {% render_field form.prop class="form-control" %}
        </div>
      </div>

      <div class="col-9"></div>
      <div class="col-2">
        <button class="btn btn-bold btn-primary" type="submit">Siguiente</button>
      </div>
    </form>
  </div>
{% endblock %}

templates/properties/properties.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block path %}
  Mis Propiedades
{% endblock %}

{% block content %}
  <h3>Mis propiedades <a href="{% url 'add_property_location' %}" class="btn btn-primary pull-right">Añadir</a></h3>
  <div class="row">
    {% for property in properties %}
      <div class="col-lg-4">
        <section class="card card-shadowed">
          <article class="gallery-item">
            <div class="ribbon-block">
              <div class="ribbon right-top">
                <!-- <div class="ribbon red right-top">
                            <i class="fa fa-heart"></i>
                        </div>
                -->
                <span>Status</span>
              </div>
              {% if property.image %}
                <img class="gallery-picture" src="{{ property.image.url }}" alt="" width="100%">
              {% else %}
                <img class="gallery-picture" src="{% static 'img/gall-img-4.jpg' %}" alt="" width="100%">
              {% endif %}
            </div>

            <div class="card-block-properties">
              <h4 class="card-title">{{ property.location }}, {{ property.number }}</h4>
              <p class="card-text fs-14" style="height:60px;">{{ property.description | truncatechars:120 }}</p>
              <div class="row" style="height:30px;">
                <div class="col-4 pr-5 fs-12"><i class="fa fa-map-marker" style="width:15px;"></i>{{ property.location | truncatechars:18 }}</div><!--City-->
                <div class="col-4 pr-5 fs-12"><i class="fa fa-home"></i>&nbsp {{ property.get_prop_type_display }}</div>
                <div class="col-4 pr-5 fs-12"><i class="fa fa-crop"></i>&nbsp {{ property.sqm }} m<sup>2</sup></div>
              </div>
              <div class="row" style="height:30px;">
                <div class="col-4 pr-5 fs-12"><i class="fa fa-eur"></i>&nbsp {{ property.price }}</div>
                <div class="col-4 pr-5 fs-12"><i class="fa fa-bed"></i>&nbsp {{ property.num_bedrooms }}</div>
                <div class="col-4 pr-5 fs-12"><i class="fa fa-bathtub"></i>&nbsp {{ property.num_bathrooms }}</div>
              </div>
              <div class="row" style="height:30px;">
                <div class="col-4 pr-5 fs-12"><i class="fa fa-car"></i>&nbsp {{ property.garage }}</div>
                <div class="col-4 pr-5 fs-12"><i class="fa fa-object-group"></i>&nbsp <!--Has Map?--></div>
                <div class="col-4 pr-5 fs-12"><i class="fa fa-camera"></i>&nbsp <!--Has photography?--></div>
              </div>
              <br>
              <div class="row">
                <div class="col-6 text-right">
                  <a href="{% url 'property_detail' pk=property.pk %}" class="btn btn-inline btn-secondary-outline" style="width:120px;">Ver</a>
                </div>
                <div class="col-6 text-left">
                  <a href="{% url 'edit_property_location' pk=property.pk %}" class="btn btn-primary" style="width:120px;">Editar</a>
                </div>
              </div>
            </div>
          </article>
        </section>
      </div>
    {% endfor %}

    {% for no_property in no_properties %}
      <div class="col-lg-4">
        <section class="card bright">
          <img src="{% static '/img/property_placeholder.png' %}" />
        </section>
      </div>
    {% endfor %}
  </div>
{% endblock %}